id: finally-sequential-error-first
namespace: io.kestra.tests

tasks:
  - id: seq
    type: io.kestra.plugin.core.flow.Sequential
    tasks:
      - id: ko
        type: io.kestra.plugin.core.execution.Fail

  - id: ok
    type: io.kestra.plugin.core.debug.Return
    format: "{{ task.id }}"

finally:
  - id: a1
    type: io.kestra.plugin.core.debug.Return
    format: "{{ task.id }}"
